name: SMSA Tracker

# Triggers
on:
  schedule:
    - cron: "*/1 * * * *" # every 1 minute UTC
  workflow_dispatch: # allows manual run

jobs:
  track:
    runs-on: ubuntu-latest
    permissions:
      contents: write # allow updating files

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false # disable default GitHub Actions bot credentials

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      # 4. Run tracker
      - name: Run tracker
        env:
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        run: |
          python tracker.py

      # 5. Commit & push last_status.json using GH_PAT
      - name: Push last_status.json
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "KarimMamdouh97"
          git config user.email "ads.karimmamdouh@gmail.com"
          git add last_status.json
          git commit -m "update status" || echo "No changes to commit"
          git push https://$GH_PAT@github.com/KarimMamdouh97/smsa-tracker.git main
